model_name: evo2-7b-nv

vocab_size: 512
hidden_size: 4096
# Number of long convolution filters in each hyena block. Can be smaller than `hidden_size`
num_filters: 4096
attn_layer_idxs: [3,10,17,24,31]
hcl_layer_idxs: [2,6,9,13,16,20,23,27,30]
hcm_layer_idxs: [1,5,8,12,15,19,22,26,29]
hcs_layer_idxs: [0,4,7,11,14,18,21,25,28]

hcm_filter_length: 128
hcs_filter_length: 7
num_layers: 32

# Length of the short, depthwise FIR applied to input projections
short_filter_length: 3 
num_attention_heads: 32
short_filter_bias: false # add bias to FIR
mlp_init_method: torch.nn.init.zeros_
mlp_output_init_method: torch.nn.init.zeros_
eps: 0.000001
state_size: 8
rotary_emb_base: 10000 
make_vocab_size_divisible_by: 8
inner_size_multiple_of: 16  # force GLU inner_size to be a multiple of
inner_mlp_size: 11008
log_intermediate_values: False
# Number of groups in GQA
proj_groups: 1
# Number of groups in grouped 
hyena_filter_groups: 1
hyena_filter_groups_medium: 16
hyena_filter_groups_short: 16
# Split strategy for channels
column_split_hyena: True
column_split: True
# Legacy options for MP / PP inference
model_parallel_size: 1
pipe_parallel_size: 1
tie_embeddings: True
mha_out_proj_bias: True
hyena_out_proj_bias: True
qkv_proj_bias: False
max_seqlen: 32768
max_batch_size: 1
final_norm: True 
use_flash_attn: True
use_flash_rmsnorm: False
use_flash_depthwise: False
use_flashfft: False
use_laughing_hyena: False
inference_mode: True
tokenizer_type: CharLevelTokenizer 
prefill_style: fft
mlp_activation: gelu
print_activations: False
ground_truth_activations_path: None